apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: two-java-applications
requires:
- path: ./app01
- path: ./app02
- path: ./app03
- path: ./app04
manifests:
  kustomize:
    paths:
    - kustomize/app01
    - kustomize/app02
    - kustomize/app03
    - kustomize/app04
#    - kustomize/base
deploy:
  kubectl: {}
